# .----------------.  .----------------.  .----------------.  .----------------.  .----------------.  .-----------------. .----------------.  .----------------. 
#| .--------------. || .--------------. || .--------------. || .--------------. || .--------------. || .--------------. || .--------------. || .--------------. |
#| |    _______   | || |  _________   | || |  _________   | || |  _________   | || |     _____    | || | ____  _____  | || |    ______    | || |    _______   | |
#| |   /  ___  |  | || | |_   ___  |  | || | |  _   _  |  | || | |  _   _  |  | || |    |_   _|   | || ||_   \|_   _| | || |  .' ___  |   | || |   /  ___  |  | |
#| |  |  (__ \_|  | || |   | |_  \_|  | || | |_/ | | \_|  | || | |_/ | | \_|  | || |      | |     | || |  |   \ | |   | || | / .'   \_|   | || |  |  (__ \_|  | |
#| |   '.___`-.   | || |   |  _|  _   | || |     | |      | || |     | |      | || |      | |     | || |  | |\ \| |   | || | | |    ____  | || |   '.___`-.   | |
#| |  |`\____) |  | || |  _| |___/ |  | || |    _| |_     | || |    _| |_     | || |     _| |_    | || | _| |_\   |_  | || | \ `.___]  _| | || |  |`\____) |  | |
#| |  |_______.'  | || | |_________|  | || |   |_____|    | || |   |_____|    | || |    |_____|   | || ||_____|\____| | || |  `._____.'   | || |  |_______.'  | |
#| |              | || |              | || |              | || |              | || |              | || |              | || |              | || |              | |
#| '--------------' || '--------------' || '--------------' || '--------------' || '--------------' || '--------------' || '--------------' || '--------------' |
# '----------------'  '----------------'  '----------------'  '----------------'  '----------------'  '----------------'  '----------------'  '----------------' 

#
# <-------- { INFORMATIONS } -------->
# 
# You need more Help? Docs -> https://dto.mc-plugins.org
# Join our Discord -> https://dcto.mc-plugins.org
# Visit out Website -> https://mc-plugins.org
#
 
#Size of the GUI
Settings_Size: 5

#Custom Items Section
Settings_Custom:

  List:
    - "Close"
    - "Back"
    - "Earnings"
    - "Leave"
    - "MoneyList"
    - "Skull"

  Skull:
 
    ActionList:
      - "NONE"

    Material: "name;<name>"
 
    Slot: 22

  Close:
 
    ActionList:
      - "CLOSE"

    Material: "url;http://textures.minecraft.net/texture/afd2400002ad9fbbbd0066941eb5b1a384ab9b0e48a178ee96e4d129a5208654"

    Slot: 40

  Leave:
 
    ActionList:
      - "LEAVE"

    Material: "REDSTONE"

    Slot: 41

  Earnings:
 
    ActionList:
      - "GUI;EARNINGS_ALL"
 
    Material: "EMERALD"

    Slot: 20

  MoneyList:
 
    ActionList:
      - "GUI;REWARDS"
 
    Material: "BOOK"

    Slot: 24

  Back:
 
    ActionList:
      - "GUI;MAIN"
 
    Material: "name;Mhf_ArrowLeft"

    Slot: 39

#Placeholders of the GUI
Settings_Place:
  - "<job_glass_color>:0:&8-/-"
  - "<job_glass_color>:1:&8-/-"
  - "<job_glass_color>:2:&8-/-"
  - "<job_glass_color>:3:&8-/-"
  - "<job_glass_color>:4:&8-/-"
  - "<job_glass_color>:5:&8-/-"
  - "<job_glass_color>:6:&8-/-"
  - "<job_glass_color>:7:&8-/-"
  - "<job_glass_color>:8:&8-/-"
  - "<job_glass_color>:9:&8-/-"
  - "<job_glass_color>:17:&8-/-"
  - "<job_glass_color>:18:&8-/-"
  - "<job_glass_color>:26:&8-/-"
  - "<job_glass_color>:27:&8-/-"
  - "<job_glass_color>:35:&8-/-"
  - "<job_glass_color>:36:&8-/-"
  - "<job_glass_color>:37:&8-/-"
  - "<job_glass_color>:38:&8-/-"
  - "<job_glass_color>:39:&8-/-"
  - "<job_glass_color>:40:&8-/-"
  - "<job_glass_color>:41:&8-/-"
  - "<job_glass_color>:42:&8-/-"
  - "<job_glass_color>:43:&8-/-"
  - "<job_glass_color>:44:&8-/-"