# .----------------.  .----------------.  .----------------.  .----------------.  .----------------.  .-----------------. .----------------.  .----------------. 
#| .--------------. || .--------------. || .--------------. || .--------------. || .--------------. || .--------------. || .--------------. || .--------------. |
#| |    _______   | || |  _________   | || |  _________   | || |  _________   | || |     _____    | || | ____  _____  | || |    ______    | || |    _______   | |
#| |   /  ___  |  | || | |_   ___  |  | || | |  _   _  |  | || | |  _   _  |  | || |    |_   _|   | || ||_   \|_   _| | || |  .' ___  |   | || |   /  ___  |  | |
#| |  |  (__ \_|  | || |   | |_  \_|  | || | |_/ | | \_|  | || | |_/ | | \_|  | || |      | |     | || |  |   \ | |   | || | / .'   \_|   | || |  |  (__ \_|  | |
#| |   '.___`-.   | || |   |  _|  _   | || |     | |      | || |     | |      | || |      | |     | || |  | |\ \| |   | || | | |    ____  | || |   '.___`-.   | |
#| |  |`\____) |  | || |  _| |___/ |  | || |    _| |_     | || |    _| |_     | || |     _| |_    | || | _| |_\   |_  | || | \ `.___]  _| | || |  |`\____) |  | |
#| |  |_______.'  | || | |_________|  | || |   |_____|    | || |   |_____|    | || |    |_____|   | || ||_____|\____| | || |  `._____.'   | || |  |_______.'  | |
#| |              | || |              | || |              | || |              | || |              | || |              | || |              | || |              | |
#| '--------------' || '--------------' || '--------------' || '--------------' || '--------------' || '--------------' || '--------------' || '--------------' |
# '----------------'  '----------------'  '----------------'  '----------------'  '----------------'  '----------------'  '----------------'  '----------------' 

#
# <-------- { INFORMATIONS } -------->
# 
# You need more Help? Docs -> https://dto.mc-plugins.org
# Join our Discord -> https://dcto.mc-plugins.org
# Visit out Website -> https://mc-plugins.org
#

#Name of the GUI
Settings_Name: "{language:Settings_Name}"
 
#Size of the GUI
Settings_Size: 5

#Custom Items Section
Settings_Custom:

  List:
    - "Close"
    - "Back"
    - "Earnings"
    - "Leave"
    - "MoneyList"
    - "Skull"

  Skull:

    Display: "{language:Settings_Custom.Skull.Display}"

    ActionList:
      - "NONE"

    Material: "name;<name>"
    
    Lore: "{language:Settings_Custom.Skull.Lore}"

    Slot: 22

  Close:

    Display: "{language:Settings_Custom.Close.Display}"

    ActionList:
      - "CLOSE"

    Material: "url;http://textures.minecraft.net/texture/afd2400002ad9fbbbd0066941eb5b1a384ab9b0e48a178ee96e4d129a5208654"

    Slot: 40

  Leave:

    Display: "{language:Settings_Custom.Leave.Display}"

    ActionList:
      - "LEAVE"

    Material: "REDSTONE"

    Slot: 41

  Earnings:

    Display: "{language:Settings_Custom.Earnings.Display}"

    ActionList:
      - "GUI:EARNINGS_ALL"
 
    Lore: "{language:Settings_Custom.Earnings.Lore}"

    Material: "EMERALD"

    Slot: 20

  MoneyList:

    Display: "{language:Settings_Custom.MoneyList.Display}"

    ActionList:
      - "GUI:REWARDS"

    Lore: "{language:Settings_Custom.MoneyList.Lore}"

    Material: "BOOK"

    Slot: 24

  Back:

    Display: "{language:Settings_Custom.Back.Display}"

    ActionList:
      - "GUI:MAIN"

    Lore: "{language:Settings_Custom.Back.Lore}"

    Material: "name;Mhf_ArrowLeft"

    Slot: 39

#Placeholders of the GUI
Settings_Place:
  - "BLACK_STAINED_GLASS_PANE:0:&8-/-"
  - "BLACK_STAINED_GLASS_PANE:1:&8-/-"
  - "BLACK_STAINED_GLASS_PANE:2:&8-/-"
  - "BLACK_STAINED_GLASS_PANE:3:&8-/-"
  - "BLACK_STAINED_GLASS_PANE:4:&8-/-"
  - "BLACK_STAINED_GLASS_PANE:5:&8-/-"
  - "BLACK_STAINED_GLASS_PANE:6:&8-/-"
  - "BLACK_STAINED_GLASS_PANE:7:&8-/-"
  - "BLACK_STAINED_GLASS_PANE:8:&8-/-"
  - "BLACK_STAINED_GLASS_PANE:9:&8-/-"
  - "BLACK_STAINED_GLASS_PANE:17:&8-/-"
  - "BLACK_STAINED_GLASS_PANE:18:&8-/-"
  - "BLACK_STAINED_GLASS_PANE:26:&8-/-"
  - "BLACK_STAINED_GLASS_PANE:27:&8-/-"
  - "BLACK_STAINED_GLASS_PANE:35:&8-/-"
  - "BLACK_STAINED_GLASS_PANE:36:&8-/-"
  - "BLACK_STAINED_GLASS_PANE:37:&8-/-"
  - "BLACK_STAINED_GLASS_PANE:38:&8-/-"
  - "BLACK_STAINED_GLASS_PANE:39:&8-/-"
  - "BLACK_STAINED_GLASS_PANE:40:&8-/-"
  - "BLACK_STAINED_GLASS_PANE:41:&8-/-"
  - "BLACK_STAINED_GLASS_PANE:42:&8-/-"
  - "BLACK_STAINED_GLASS_PANE:43:&8-/-"
  - "BLACK_STAINED_GLASS_PANE:44:&8-/-"