# .----------------.  .----------------.  .----------------.  .----------------.  .----------------.  .----------------.  .----------------.  .----------------.  .----------------.  .----------------.  .----------------.  .----------------. 
#| .--------------. || .--------------. || .--------------. || .--------------. || .--------------. || .--------------. || .--------------. || .--------------. || .--------------. || .--------------. || .--------------. || .--------------. |
#| |  ________    | || |      __      | || |     _____    | || |   _____      | || |  ____  ____  | || |              | || |    ___       | || | _____  _____ | || |  _________   | || |    _______   | || |  _________   | || |    _______   | |
#| | |_   ___ `.  | || |     /  \     | || |    |_   _|   | || |  |_   _|     | || | |_  _||_  _| | || |              | || |  .'   '.     | || ||_   _||_   _|| || | |_   ___  |  | || |   /  ___  |  | || | |  _   _  |  | || |   /  ___  |  | |
#| |   | |   `. \ | || |    / /\ \    | || |      | |     | || |    | |       | || |   \ \  / /   | || |    ______    | || | /  .-.  \    | || |  | |    | |  | || |   | |_  \_|  | || |  |  (__ \_|  | || | |_/ | | \_|  | || |  |  (__ \_|  | |
#| |   | |    | | | || |   / ____ \   | || |      | |     | || |    | |   _   | || |    \ \/ /    | || |   |______|   | || | | |   | |    | || |  | '    ' |  | || |   |  _|  _   | || |   '.___`-.   | || |     | |      | || |   '.___`-.   | |
#| |  _| |___.' / | || | _/ /    \ \_ | || |     _| |_    | || |   _| |__/ |  | || |    _|  |_    | || |              | || | \  `-'  \_   | || |   \ `--' /   | || |  _| |___/ |  | || |  |`\____) |  | || |    _| |_     | || |  |`\____) |  | |
#| | |________.'  | || ||____|  |____|| || |    |_____|   | || |  |________|  | || |   |______|   | || |              | || |  `.___.\__|  | || |    `.__.'    | || | |_________|  | || |  |_______.'  | || |   |_____|    | || |  |_______.'  | |
#| |              | || |              | || |              | || |              | || |              | || |              | || |              | || |              | || |              | || |              | || |              | || |              | |
#| '--------------' || '--------------' || '--------------' || '--------------' || '--------------' || '--------------' || '--------------' || '--------------' || '--------------' || '--------------' || '--------------' || '--------------' |
# '----------------'  '----------------'  '----------------'  '----------------'  '----------------'  '----------------'  '----------------'  '----------------'  '----------------'  '----------------'  '----------------'  '----------------' 
 
#
# <-------- { INFORMATIONS } -------->
# 
# You need more Help? Docs -> https://dto.mc-plugins.org
# Join our Discord -> https://dcto.mc-plugins.org
# Visit out Website -> https://mc-plugins.org
#

EnableDailyQuests: true

#
# Get new quests every 24 hours
#

GetNewEvery: 24

#
# Use false when the quests should be automatically update or a user needs to confirm in the dailyquests_confirm to get new ones
#

NeedToConfirmNewQuests: true

#
# quests gui permission
#

EnablePermissionToUseGUI: false

PermissionToUseGUI: "ultimatejobs.use.dailyquests"

#when false, a player will get no quests which require a permission if the player does not have it
CanGetQuestsWithoutNeededPermission: true