# .----------------.  .----------------.  .-----------------. .----------------.  .----------------.  .----------------.
#| .--------------. || .--------------. || .--------------. || .--------------. || .--------------. || .--------------. |
#| |     ______   | || |     ____     | || | ____  _____  | || |  _________   | || |     _____    | || |    ______    | |
#| |   .' ___  |  | || |   .'    `.   | || ||_   \|_   _| | || | |_   ___  |  | || |    |_   _|   | || |  .' ___  |   | |
#| |  / .'   \_|  | || |  /  .--.  \  | || |  |   \ | |   | || |   | |_  \_|  | || |      | |     | || | / .'   \_|   | |
#| |  | |         | || |  | |    | |  | || |  | |\ \| |   | || |   |  _|      | || |      | |     | || | | |    ____  | |
#| |  \ `.___.'\  | || |  \  `--'  /  | || | _| |_\   |_  | || |  _| |_       | || |     _| |_    | || | \ `.___]  _| | |
#| |   `._____.'  | || |   `.____.'   | || ||_____|\____| | || | |_____|      | || |    |_____|   | || |  `._____.'   | |
#| |              | || |              | || |              | || |              | || |              | || |              | |
#| '--------------' || '--------------' || '--------------' || '--------------' || '--------------' || '--------------' |
# '----------------'  '----------------'  '----------------'  '----------------'  '----------------'  '----------------'

CheckForUpdates: true

LoadJobsFrom: "plugins/UltimateJobs/jobs/"

KickOnReload: true

#default 180 seconds
#the cache gets saved on join or quit, a low value here can create TPS issues. Change on own risk
Cache_Saved_Every: 180

#change on own risk
ExecutorServiceThreads: 1

#how many jobs can a player have by default? 
# 0 equals 1!!!
MaxDefaultJobs: 0

#if enabled, players can own default jobs
EnabledDefaultJobs: false

#when a player gets created, he will own this job
DefaultJobs:
  - "MINER"

#do you want to use the levels?
Enable_Levels: true

Levels:

  #get a firework on a level up?
  FireWork: true

#you can find the types in the github wiki
Sounds:

  LEVEL_UP:

    Sound: "ENTITY_PLAYER_LEVELUP"

    Volume: 1

    Pitch: 1

#Date-Format
Date: "dd/MM/yyyy"

#format of example money, 10.05
Format: "0.00"
 
#config of the main gui
Main_Name: "&b&lJobs Menu"

#options to the job items
Jobs:

  #you want the "Are you Sure to buy this Job" GUI?
  AreYouSureGUIonBuy: true
  
  MaxEarnings:
    #can the player earn exp when the max. amount is reached?
    IfReached_Can_Earn_Exp: false
    
    #can the player earn points when the max. amount is reached?
    IfReached_Can_Earn_Points: false
    
    #can the player's stats change when the max. amount is reached?
    IfReached_Can_Stats: false

  Lore:

    Bought:
      - "&7"
      - "&aYou own this Job."

    In:
      - "&7"
      - "&bYou are in this Job."

    Price:
      - "&7"
      - "&cClick to buy this job for <price> Dollars."

# -> 3 * 9
Main_Size: 5

Main_Custom:

  List:
    - "Close"
    - "Leave"
    - "Info"

  Close:

    Display: "&cClose Menu"

    Action: "CLOSE"

    Material: "RED_DYE"

    Slot: 41

  Leave:

    Display: "&4Leave all Jobs"

    Action: "LEAVE"

    Lore:
      - "&7Click here to leave all jobs"

    Material: "BARRIER"

    Slot: 40

  Info:

    Display: "&bInformations"

    Action: "NOTHING"

    Lore:
      - "&8&m-------------------"
      - "&cWhy i should get an job?"
      - "&7"
      - "&7You need an Job to earn money, "
      - "&7to raise your Kids! :)"
      - "&8"
      - "&8-> &7You can have &c<max> &7Jobs."
      - "&8-> &7You have &a<points> &7Points."

    Material: "BEACON"

    Slot: 39

Main_Place:
  - "BLACK_STAINED_GLASS_PANE:0:&7"
  - "BLACK_STAINED_GLASS_PANE:1:&7"
  - "BLACK_STAINED_GLASS_PANE:2:&7"
  - "BLACK_STAINED_GLASS_PANE:3:&7"
  - "BLACK_STAINED_GLASS_PANE:4:&7"
  - "BLACK_STAINED_GLASS_PANE:5:&7"
  - "BLACK_STAINED_GLASS_PANE:6:&7"
  - "BLACK_STAINED_GLASS_PANE:7:&7"
  - "BLACK_STAINED_GLASS_PANE:8:&7"
  - "BLACK_STAINED_GLASS_PANE:9:&7"
  - "BLACK_STAINED_GLASS_PANE:10:&7"
  - "BLACK_STAINED_GLASS_PANE:11:&7"
  - "BLACK_STAINED_GLASS_PANE:17:&7"
  - "BLACK_STAINED_GLASS_PANE:18:&7"
  - "BLACK_STAINED_GLASS_PANE:26:&7"
  - "BLACK_STAINED_GLASS_PANE:27:&7"
  - "BLACK_STAINED_GLASS_PANE:35:&7"
  - "BLACK_STAINED_GLASS_PANE:36:&7"
  - "BLACK_STAINED_GLASS_PANE:37:&7"
  - "BLACK_STAINED_GLASS_PANE:38:&7"
  - "BLACK_STAINED_GLASS_PANE:39:&7"
  - "BLACK_STAINED_GLASS_PANE:40:&7"
  - "BLACK_STAINED_GLASS_PANE:41:&7"
  - "BLACK_STAINED_GLASS_PANE:42:&7"
  - "BLACK_STAINED_GLASS_PANE:43:&7"
  - "BLACK_STAINED_GLASS_PANE:44:&7"

#options menu
Settings_Name: "&bJob Options &8- <job>"

Settings_Size: 3

Settings_Custom:

  List:
    - "Close"
    - "Back"
    - "Earnings"
    - "Leave"
    - "MoneyList"

  Close:

    Display: "&cClose Menu"

    Action: "CLOSE"

    Material: "RED_DYE"

    Slot: 16

  Leave:

    Display: "&c&lLeave this Job"

    Action: "LEAVE"

    Material: "REDSTONE"

    Slot: 15

  Earnings:

    Display: "&6My Earnings this Month"

    Action: "COMMAND"

    Command: "jobs earnings <job>"

    Lore:
      - "&7This works only when the addon is installed."

    Material: "EMERALD"

    Slot: 10

  MoneyList:

    Display: "&4See Earnings for different Blocks"

    Action: "COMMAND"

    Command: "jobs rewards <job>"

    Lore:
      - "&7This works only when the addon is installed."

    Material: "BOOK"

    Slot: 11

  Back:

    Display: "&4Go Back"

    Action: "BACK"

    Lore:
      - "&7Click here to get back to the main menu"

    Material: "BARRIER"

    Slot: 13

Settings_Place:
  - "BLACK_STAINED_GLASS_PANE:0:&7"
  - "BLACK_STAINED_GLASS_PANE:1:&7"
  - "BLACK_STAINED_GLASS_PANE:2:&7"
  - "BLACK_STAINED_GLASS_PANE:3:&7"
  - "BLACK_STAINED_GLASS_PANE:4:&7"
  - "BLACK_STAINED_GLASS_PANE:5:&7"
  - "BLACK_STAINED_GLASS_PANE:6:&7"
  - "BLACK_STAINED_GLASS_PANE:7:&7"
  - "BLACK_STAINED_GLASS_PANE:8:&7"
  - "BLACK_STAINED_GLASS_PANE:9:&7"
  - "BLACK_STAINED_GLASS_PANE:17:&7"
  - "BLACK_STAINED_GLASS_PANE:18:&7"
  - "BLACK_STAINED_GLASS_PANE:19:&7"
  - "BLACK_STAINED_GLASS_PANE:20:&7"
  - "BLACK_STAINED_GLASS_PANE:21:&7"
  - "BLACK_STAINED_GLASS_PANE:22:&7"
  - "BLACK_STAINED_GLASS_PANE:23:&7"
  - "BLACK_STAINED_GLASS_PANE:24:&7"
  - "BLACK_STAINED_GLASS_PANE:25:&7"
  - "BLACK_STAINED_GLASS_PANE:26:&7"

#Are you sure gui
AreYouSureGUI_Name: "&7You want to buy <job>&7?"

AreYouSureGUI_Size: 3

AreYouSureItems:

  Button_NO:
  
    Icon: "RED_DYE"
    
    Display: "&cNo"
    
    Slot: 15
    
    Lore:
      - "&7Cancel this progress."

  Button_YES:
  
    Icon: "GREEN_DYE"
    
    Display: "&aYes, I'm Sure"
    
    Slot: 11
    
    Lore:
      - "&7You want to buy this Job?"

AreYouSureGUI_Custom:

  List:
    - "Back"

  Back:

    Display: "&4Go Back"

    Action: "BACK"

    Lore:
      - "&7Click here to get back to the main menu"

    Material: "BARRIER"

    Slot: 26

AreYouSureGUI_Place:
  - "BLACK_STAINED_GLASS_PANE:13:&7"