# .----------------.  .----------------.  .-----------------. .----------------.  .----------------.  .----------------.
#| .--------------. || .--------------. || .--------------. || .--------------. || .--------------. || .--------------. |
#| |     ______   | || |     ____     | || | ____  _____  | || |  _________   | || |     _____    | || |    ______    | |
#| |   .' ___  |  | || |   .'    `.   | || ||_   \|_   _| | || | |_   ___  |  | || |    |_   _|   | || |  .' ___  |   | |
#| |  / .'   \_|  | || |  /  .--.  \  | || |  |   \ | |   | || |   | |_  \_|  | || |      | |     | || | / .'   \_|   | |
#| |  | |         | || |  | |    | |  | || |  | |\ \| |   | || |   |  _|      | || |      | |     | || | | |    ____  | |
#| |  \ `.___.'\  | || |  \  `--'  /  | || | _| |_\   |_  | || |  _| |_       | || |     _| |_    | || | \ `.___]  _| | |
#| |   `._____.'  | || |   `.____.'   | || ||_____|\____| | || | |_____|      | || |    |_____|   | || |  `._____.'   | |
#| |              | || |              | || |              | || |              | || |              | || |              | |
#| '--------------' || '--------------' || '--------------' || '--------------' || '--------------' || '--------------' |
# '----------------'  '----------------'  '----------------'  '----------------'  '----------------'  '----------------'

CheckForUpdates: true

LoadJobsFrom: "plugins/UltimateJobs/jobs/"

KickOnReload: true

CancelEvents: false

#default 180 seconds
#the cache gets saved on join or quit, a low value here can create TPS issues. Change on own risk
Cache_Saved_Every: 180

#change on own risk
ExecutorServiceThreads: 1

#how many jobs can a player have by default? 
# 0 equals 1!!!
MaxDefaultJobs: 0

#if enabled, players can own default jobs
EnabledDefaultJobs: false

#when a player gets created, he will own this job
DefaultJobs:
  - "MINER"

#do you want to use the levels?
Enable_Levels: true

#Date-Format
Date: "dd/MM/yyyy"

#format of example money, 10.05
Format: "0.00"

# .----------------.  .----------------.  .----------------.  .----------------. 
#| .--------------. || .--------------. || .--------------. || .--------------. |
#| |     _____    | || |     ____     | || |   ______     | || |    _______   | |
#| |    |_   _|   | || |   .'    `.   | || |  |_   _ \    | || |   /  ___  |  | |
#| |      | |     | || |  /  .--.  \  | || |    | |_) |   | || |  |  (__ \_|  | |
#| |   _  | |     | || |  | |    | |  | || |    |  __'.   | || |   '.___`-.   | |
#| |  | |_' |     | || |  \  `--'  /  | || |   _| |__) |  | || |  |`\____) |  | |
#| |  `.___.'     | || |   `.____.'   | || |  |_______/   | || |  |_______.'  | |
#| |              | || |              | || |              | || |              | |
#| '--------------' || '--------------' || '--------------' || '--------------' |
# '----------------'  '----------------'  '----------------'  '----------------'
 
#can a player get money from mobs which are spawned by a spawner? 
CanEarnMoneyFromSpawnerMobs: false

#options to the job items
Jobs:

  #you want the "Are you Sure to buy this Job" GUI?
  AreYouSureGUIonBuy: true
  
  MaxEarnings:
    #can the player earn exp when the max. amount is reached?
    IfReached_Can_Earn_Exp: false
    
    #can the player earn points when the max. amount is reached?
    IfReached_Can_Earn_Points: false
    
    #can the player's stats change when the max. amount is reached?
    IfReached_Can_Stats: false

 
# .----------------.  .----------------.  .----------------.  .-----------------. .----------------.  .----------------. 
#| .--------------. || .--------------. || .--------------. || .--------------. || .--------------. || .--------------. |
#| |    _______   | || |     ____     | || | _____  _____ | || | ____  _____  | || |  ________    | || |    _______   | |
#| |   /  ___  |  | || |   .'    `.   | || ||_   _||_   _|| || ||_   \|_   _| | || | |_   ___ `.  | || |   /  ___  |  | |
#| |  |  (__ \_|  | || |  /  .--.  \  | || |  | |    | |  | || |  |   \ | |   | || |   | |   `. \ | || |  |  (__ \_|  | |
#| |   '.___`-.   | || |  | |    | |  | || |  | '    ' |  | || |  | |\ \| |   | || |   | |    | | | || |   '.___`-.   | |
#| |  |`\____) |  | || |  \  `--'  /  | || |   \ `--' /   | || | _| |_\   |_  | || |  _| |___.' / | || |  |`\____) |  | |
#| |  |_______.'  | || |   `.____.'   | || |    `.__.'    | || ||_____|\____| | || | |________.'  | || |  |_______.'  | |
#| |              | || |              | || |              | || |              | || |              | || |              | |
#| '--------------' || '--------------' || '--------------' || '--------------' || '--------------' || '--------------' |
# '----------------'  '----------------'  '----------------'  '----------------'  '----------------'  '----------------' 

#you can find the types in the github wiki
Sounds:

  OPEN_LEVELS_GUI:

    Sound: "BLOCK_CHEST_OPEN"

    Volume: 1

    Pitch: 4
 
  OPEN_REWARDS_GUI:

    Sound: "BLOCK_CHEST_OPEN"

    Volume: 1

    Pitch: 4

  OPEN_SELF_STATS_GUI:

    Sound: "BLOCK_CHEST_OPEN"

    Volume: 1

    Pitch: 4
    
  OPEN_OTHER_STATS_GUI:

    Sound: "BLOCK_CHEST_OPEN"

    Volume: 1

    Pitch: 4
    
  OPEN_HELP_GUI:

    Sound: "BLOCK_CHEST_OPEN"

    Volume: 1

    Pitch: 4

  OPEN_SURE_GUI:

    Sound: "BLOCK_CHEST_OPEN"

    Volume: 1

    Pitch: 4

  OPEN_MAIN:

    Sound: "BLOCK_CHEST_OPEN"

    Volume: 1

    Pitch: 4
    
  OPEN_SETTINGS:

    Sound: "BLOCK_CHEST_OPEN"

    Volume: 1

    Pitch: 4
    
  LEVEL_UP:

    Sound: "ENTITY_PLAYER_LEVELUP"

    Volume: 1

    Pitch: 2

# .----------------.  .----------------.  .----------------.  .----------------.  .----------------.  .----------------.  .----------------. 
#| .--------------. || .--------------. || .--------------. || .--------------. || .--------------. || .--------------. || .--------------. |
#| |  _______     | || |  _________   | || | _____  _____ | || |      __      | || |  _______     | || |  ________    | || |    _______   | |
#| | |_   __ \    | || | |_   ___  |  | || ||_   _||_   _|| || |     /  \     | || | |_   __ \    | || | |_   ___ `.  | || |   /  ___  |  | |
#| |   | |__) |   | || |   | |_  \_|  | || |  | | /\ | |  | || |    / /\ \    | || |   | |__) |   | || |   | |   `. \ | || |  |  (__ \_|  | |
#| |   |  __ /    | || |   |  _|  _   | || |  | |/  \| |  | || |   / ____ \   | || |   |  __ /    | || |   | |    | | | || |   '.___`-.   | |
#| |  _| |  \ \_  | || |  _| |___/ |  | || |  |   /\   |  | || | _/ /    \ \_ | || |  _| |  \ \_  | || |  _| |___.' / | || |  |`\____) |  | |
#| | |____| |___| | || | |_________|  | || |  |__/  \__|  | || ||____|  |____|| || | |____| |___| | || | |________.'  | || |  |_______.'  | |
#| |              | || |              | || |              | || |              | || |              | || |              | || |              | |
#| '--------------' || '--------------' || '--------------' || '--------------' || '--------------' || '--------------' || '--------------' |
# '----------------'  '----------------'  '----------------'  '----------------'  '----------------'  '----------------'  '----------------'

Reward:

  Enable_BossBar: true
  
  Enable_Message: false
  
  Enabled_Actionbar: false
  
MaxEarningsReached:

  Enable_BossBar: true
  
  Enable_Message: false
  
  Enabled_Actionbar: false
  
# .----------------.  .----------------.  .----------------.  .----------------.  .----------------.  .----------------. 
#| .--------------. || .--------------. || .--------------. || .--------------. || .--------------. || .--------------. |
#| |   _____      | || |  _________   | || | ____   ____  | || |  _________   | || |   _____      | || |    _______   | |
#| |  |_   _|     | || | |_   ___  |  | || ||_  _| |_  _| | || | |_   ___  |  | || |  |_   _|     | || |   /  ___  |  | |
#| |    | |       | || |   | |_  \_|  | || |  \ \   / /   | || |   | |_  \_|  | || |    | |       | || |  |  (__ \_|  | |
#| |    | |   _   | || |   |  _|  _   | || |   \ \ / /    | || |   |  _|  _   | || |    | |   _   | || |   '.___`-.   | |
#| |   _| |__/ |  | || |  _| |___/ |  | || |    \ ' /     | || |  _| |___/ |  | || |   _| |__/ |  | || |  |`\____) |  | |
#| |  |________|  | || | |_________|  | || |     \_/      | || | |_________|  | || |  |________|  | || |  |_______.'  | |
#| |              | || |              | || |              | || |              | || |              | || |              | |
#| '--------------' || '--------------' || '--------------' || '--------------' || '--------------' || '--------------' |
# '----------------'  '----------------'  '----------------'  '----------------'  '----------------'  '----------------' 

Levels:

  Firework: true
  
  BroadCastLevelUps: true
  
  #title on levelup?
  Enable_Title: true
  
  #message on levelup?
  Enable_Message: false
  
  #actionbar on levelup?
  Enabled_Actionbar: false