main: de.warsteiner.jobs.UltimateJobs
version: 0.3.1
name: UltimateJobs
author: Warsteiner37
api-version: 1.13
softdepend: [WorldGuard, AlonsoLevels, WorldEdit, PlaceHolderAPI]
depend: [SimpleAPI]

commands:
  jobs:
    aliases: [job]
  jobsadmin:
    aliases: [jba]