main: de.warsteiner.jobs.UltimateJobs
version: Iron-0.5.3
name: UltimateJobs
author: Warsteiner37
api-version: 1.17
depend: [Vault]
softdepend: [WorldGuard, WorldEdit, PlaceHolderAPI, MythicMobs, ItemsAdder, NoteBlockAPI]
description: Let Players work with this Jobs Plugin!
website: https://mc-plugins.org

commands:
  jobs:
    aliases: [job]
  jobsadmin:
    aliases: [jba]