main: de.warsteiner.jobs.UltimateJobs
version: Iron-0.5.0
name: UltimateJobs
author: Warsteiner37
api-version: 1.17
depend: [Vault]
softdepend: [WorldGuard, WorldEdit, PlaceHolderAPI, MythicMobs, ItemsAdder]
description: Let Players work with this high quality Jobs Plugin!
website: https://mc-plugins.org

commands:
  jobs:
    aliases: [job]
  jobsadmin:
    aliases: [jba]