name: UltimateJobs
description: Let players work with this Jobs plugin!
version: ${project.version}
authors: [Optic_Fusion1, Warsteiner37]
main: optic_fusion1.jobs.UltimateJobs
api-version: 1.14
depend: [Vault]
softdepend: [WorldGuard, WorldEdit, PlaceHolderAPI, MythicMobs, ItemsAdder, NoteBlockAPI]
commands:
  jobs:
    aliases: [job]
  jobsadmin:
    aliases: [jba]