package optic_fusion1.jobs.gui;

public enum GUIType {

    MAIN, CONFIRM, SETTINGS, STATS_SELF, STATS_OTHER,
    LANGUAGE, HELP, EARNINGS_ALL, EARNINGS_JOB, LEVELS, REWARDS, WITHDRAW, CONFIRM_WITHDRAW, CONFIRM_LEAVE, GLOBAL_RANKING, JOB_RANKING;

}
